#!/usr/bin/env python3
# -*- coding: utf-8 -*-

__author__ = 'Felix Yu'

cookies = {}
index_url = "http://index.baidu.com/api/SearchApi/index?area=0&word="
index_date_range = "&days=7"


def get_baidu_index(keyword):
    index_result_dict = {'kw':self.keyword,'all':'--','pc':'--','mob':'--'}
    url = index_url+keyword+index_date_range
    req = requests.get(url=url,cookies=cookies)
    res = req.text
    data_json = json.loads(res)
    if data_json['status'] == 0:
        index_result_dict = dict(kw=self.keyword,all=data_json['data']['generalRatio'][0]['all']['avg'],pc = data_json['data']['generalRatio'][0]['pc']['avg'],mob = data_json['data']['generalRatio'][0]['wise']['avg'])
    else:
        pass
    return index_result_dict
